######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 8 15:15:37 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

<<<<<<< HEAD
# Input
HEADERS += bus.h bussimulator.h busstop.h mainwindow.h
SOURCES += bus.cpp \
           bussimulator.cpp \
           busstop.cpp \
           main.cpp \
           mainwindow.cpp
=======

SOURCES += main.cpp\
        mainwindow.cpp \

HEADERS  += mainwindow.h \
>>>>>>> cb39c215f8b83193498997882c9ad548ddc27918
